# Generated by Django 5.0 on 2023-12-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carshop', '0002_rename_brand_car_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='catagory',
            new_name='brand',
        ),
    ]
